[workspace]
authors = ["Abdulai Hallowell <thhal3@morgan.edu>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "life"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.1.0.dev2025120505,<0.27"
pypdf2 = ">=3.0.1,<4"
