[workspace]
authors = ["rosaiju <rosai2@morgan.edu>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "life"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.1.0.dev2025120323,<0.27"
pypdf2 = ">=3.0.1,<4"
numpy = ">=2.3.5,<3"
